# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://rfitzsimons.github.io"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: RONAN FITZSIMONS
# Description of the Site
description: Data Analyst - Portfolio Website
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ronanfitzsimons@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: ronanfitzsimons
github_username:  rfitzsimons
youtube_channel_id: 
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Ronan Fitzsimons
# URL for the Image of the Author
author-image: https://pbs.twimg.com/profile_images/763711230293016576/Pem49DIU_400x400.jpg
## old https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png 
# 60 Words About the Author
author-about: Versatile data professional with a background in research, design, technology & innovation. Experience collecting, transforming and organizing data for analysis. Strong communication, organisational and analytical skills, collaborating with multi-disciplinary stakeholders to affect change and achieve business goals. Excellent understanding and proficiency of platforms for effective data analyses, including SQL, Big Query, Excel, R and Tableau. Recently completed the Google Data Analytics Professional Certificate - a rigorous, hands-on program that covers the entire scope of the data analysis process.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/rfitzsimons

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
